language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "pypy3"
#  allow_failures:
#    - python: 3.8-dev

install:
  - pip -q install -e .[tests]
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8* ]]; then
    pip install flake8;
    pip install pytest-cov;
    fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8* ]]; then
    flake8 .;
    pytest -v --cov=pyongc tests/;
    else
    pytest -v;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8* ]]; then
    coveralls;
    fi

